### ISSUE TITLE
Error plotting glmmTMB model with weights argument

### ISSUE THREAD

**Issue by erinsauer** [pbreheny/visreg#67] opened 2019-03-04 16:53 UTC
First, thanks for making an awesome package and keeping up with user issues! I'm having some trouble plotting a `glmmTMB` model with a `weights` argument. When I remove the `weights` argument from model and run the same code, the `visreg` code works fine. There is no missing data in the `in.var` column. Thanks!

```
ENDmodel<-glmmTMB(ln.or~host.bio1*Temp+logdose+lifestage+
              (1|genus.and.species)+( 1|ID)+ (1|bd.ID),
                family="gaussian", data=END, weights=in.var, 
                dispformula = ~1, doFit=TRUE)
 visreg(ENDmodel, "Temp", by="host.bio1.10", breaks=2,   
        points=list(col="black", cex=1.5, pch=21), 
        line.par=list(lty=2, col="black", lwd=3), 
        strip=F, par.strip.text = list(col = "transparent"), 
        xlab="Laboratory temperature (C)", 
        ylab="Mortality relative to controls (ln odds ratio)", 
        scales=list(y=list(at=c(0,1,2,3,4,5),limits=c(0, 5)), 
        alternating=FALSE, tck=c(1,0)), 
        jitter=TRUE, fill.par=list(col=c("grey")))
Error in model.frame.default(weights = in.var, drop.unused.levels = TRUE,  : 
  variable lengths differ (found for '(weights)')
```

**Comment by pbreheny** [comment] 2019-03-07 18:56
Hi Erin,

This would seem to be a problem with `glmmTMB`, not with `visreg`:

```
library(glmmTMB)
w <- runif(nrow(Salamanders))
fit <- glmmTMB(count~ mined + (1|site), zi=~mined, family=poisson, data=Salamanders, weights=w)
predict(fit, newdata = Salamanders[1:5,])
```

produces

```
Error in model.frame.default(weights = w, drop.unused.levels = TRUE, formula = ~mined +  : 
  variable lengths differ (found for '(weights)')
```

In other words, it seems that `predict.glmmTMB()` does not work if the model was fit with weights.  You should let the maintainer of the glmmTMB know about this.

**Comment by erinsauer** [comment] 2019-03-07 20:20
Hi Patrick,

I actually tested `predict` before posting this issue, thinking that this might be the problem. But when I use `predict` with my `glmmTMB` model it seems to work fine (no error message). You may be getting that error because `w` is not part of your data frame so it has a different length than `Salamanders[1:5,]` which is only 5 rows. 

I tried running your code without limiting the length of `Salamanders` and it worked fine.

Thanks!

Erin

**Comment by pbreheny** [comment] 2019-03-08 22:47
Hmm, interesting.  The issue is that `visreg` needs to be able to make predictions not just for rows of the data that appear in the data frame, but for hypothetical rows that could appear in the data frame -- this is the line being plotted.  It seems to me that there are two possibilities:

1. `predict.glmmTMB` doesn't actually need weights in order to make predictions.  If this is the case, it shouldn't output an error if weights aren't supplied.
2. `predict.glmmTMB` *does* need weights in order to make predictions.  If this is the case, it seems a little hopeless since `visreg` isn't going to know how to set up those weights.

I guess there is perhaps a third possibility:

3. `predict.glmmTMB` could potentially depend on weights, but a reasonable default would just be to give everything a default weight of 1 if weights aren't supplied.

I have no idea what `glmmTMB` is, so I don't know which one of these is correct, but I guess I'm sort of inclined to stand by my original conclusion that `predict.glmmTMB` should still work if weights aren't supplied, and that's something that should be fixed on the `glmmTMB` end.

All they would have to do is add the line

```r
mf$weights <- rep(1, nrow(mf$data))
```

with perhaps some sort of check to only do this if weights aren't supplied or something.

As a workaround, not sure how you feel about this, but you can write your own `predict.glmmTMB` function.  Just copy the existing one, add one line:

```r
mf$na.action <- na.action   # This line exists already
mf$weights <- rep(1, nrow(mf$data))   # This is the line you're adding
```

then run

```r
environment(predict.glmmTMB) <- asNamespace('glmmTMB')
```

And then `visreg()` works fine.

**Comment by mattjohnsonhsu** [comment] 2022-08-01 20:14
I get the same error with visreg using a simple glm model with weights (not glmmTMB):

>forest_rsf_deermcp <- glm(case_~forest, family = "binomial", data = ua_95, weights = weight)
>visreg(forest_rsf_deermcp)
Error in eval(extras, data, env) : object 'weight' not found

**Comment by pbreheny** [comment] 2022-08-01 20:53
Is there a variable called `weight` in the `ua_95` data set? If so, the code will work. For example:

```r
library(visreg)
df <- data.frame(y=rbinom(1000, 1, 0.5), x=runif(1000), w=1+rpois(1000, 5))
fit <- glm(y~x, data=df, family=binomial, weights=w)
visreg(fit)
```

**Comment by mattjohnsonhsu** [comment] 2022-08-03 22:24
Yes, there is a variable called weight.

Fitting the mode works, but visreg does not.

Matt
***********************************************************************************
Matt Johnson
Professor, Wildlife Habitat Ecology
Webpage <https://wildlife.humboldt.edu/people/matthew-johnson>
Director, HSI-STEM grant <https://hsistem.humboldt.edu/hsi-stem-grant>
Co-PI, Échale Ganas USDA grant <https://echaleganas.humboldt.edu/>
Department of Wildlife
Cal Poly Humboldt (formerly Humboldt State University)
Arcata, CA 95521
Phone: (707) 826-3218
FAX :  (707) 826-4060
email: ***@***.***
***********************************************************************************

**Comment by pbreheny** [comment] 2022-08-03 22:28
Without a [reproducible example](https://myweb.uiowa.edu/pbreheny/reproducible.html), there's nothing I can do to help. The code itself would seem to work -- see my example -- so presumably the problem lies in some code/data you haven't provided.

**Comment by mattjohnsonhsu** [comment] 2022-08-03 22:35
Thanks for the quick reply.

I'll distill the data & code down to something I can send that's
reproducible. One moment...

Matt
***********************************************************************************
Matt Johnson
Professor, Wildlife Habitat Ecology
Webpage <https://wildlife.humboldt.edu/people/matthew-johnson>
Director, HSI-STEM grant <https://hsistem.humboldt.edu/hsi-stem-grant>
Co-PI, Échale Ganas USDA grant <https://echaleganas.humboldt.edu/>
Department of Wildlife
Cal Poly Humboldt (formerly Humboldt State University)
Arcata, CA 95521
Phone: (707) 826-3218
FAX :  (707) 826-4060
email: ***@***.***
***********************************************************************************

**Comment by mattjohnsonhsu** [comment] 2022-08-03 22:53
Hi Patrick,

Attached is the data.

And here's the code distilled to the visreg error I can't seem to figure
out.  Any help would be appreciated.

Thanks

### reproducible visreg error with weights ####

install.packages("glmmTMB")
library(glmmTMB)
library(visreg)

goats.data <- read.csv('data/goats.data_scaled_wtd.csv')
gm.1_rand_slopeELEV_wt <- glmmTMB(STATUS ~
poly(ELEVATION,2)+SLOPE+ET+poly(HLI,2) + (1|ID) + (0+ELEVATION |ID),
family=binomial(), data = goats.data, weights = weight)
summary(gm.1_rand_slopeELEV_wt)

visreg(gm.1_rand_slopeELEV_wt, scale="response")

###########################################

Thanks,

Matt
***********************************************************************************
Matt Johnson
Professor, Wildlife Habitat Ecology
Webpage <https://wildlife.humboldt.edu/people/matthew-johnson>
Director, HSI-STEM grant <https://hsistem.humboldt.edu/hsi-stem-grant>
Co-PI, Échale Ganas USDA grant <https://echaleganas.humboldt.edu/>
Department of Wildlife
Cal Poly Humboldt (formerly Humboldt State University)
Arcata, CA 95521
Phone: (707) 826-3218
FAX :  (707) 826-4060
email: ***@***.***
***********************************************************************************

**Closed** 2022-08-04 16:59 UTC

**Comment by pbreheny** [comment] 2022-08-04 17:05
1. First of all, contrary to your claim, this works fine with glm (your data, your model, just replacing glmmTMB with glm).
2. I still think that fundamentally, this is a problem with `predict.glmmTMB()` in the sense that it should allow the user to make predictions for new observations without requiring weights.
3. However, I just committed a change that allows an easy workaround to this limitation in glmmTMB. You can directly set the weights for the new predictions to be 1 (or something else, I guess):
```r
visreg(gm.1_rand_slopeELEV_wt, scale="response", cond=list(weight=1))
```
This should now function as you want it to (keep in mind that you need to run `remotes::install_github("pbreheny/visreg")` first).

This functionality will appear in visreg 2.7.1.

**Comment by mattjohnsonhsu** [comment] 2022-08-04 21:27
Hi Patrick,

I had a min back at my computer and ran what you suggested -- worked
great!  Many thanks!

Cheers,

Matt
***********************************************************************************
Matt Johnson
Professor, Wildlife Habitat Ecology
Webpage <https://wildlife.humboldt.edu/people/matthew-johnson>
Director, HSI-STEM grant <https://hsistem.humboldt.edu/hsi-stem-grant>
Co-PI, Échale Ganas USDA grant <https://echaleganas.humboldt.edu/>
Department of Wildlife
Cal Poly Humboldt (formerly Humboldt State University)
Arcata, CA 95521
Phone: (707) 826-3218
FAX :  (707) 826-4060
email: ***@***.***
***********************************************************************************

**Comment by pbreheny** [comment] 2023-11-06 16:46
2.7.1 doesn't exist yet; 2.7.0.8 is the most current version. Can you provide a [reproducible example](https://myweb.uiowa.edu/pbreheny/reproducible.html)?

**Comment by milkweedgirl** [comment] 2023-11-07 15:40
Hi Patrick- could I email you the dataset I am working with to show you my
issue?

 thank-you, Emma

my school email: ***@***.***

**Comment by pbreheny** [comment] 2023-11-07 16:42
Sure

**Comment by e-eberhardt** [comment] 2025-12-06 03:03
Hi all,

I am having this issue as well still, with visreg having issues with the weights argument being included in a glm. I am getting similar errors where when the weights argument is included. I have tried some of the solutions on this thread such as cond=list(weight=1) being included within the visreg string.

I will try and attach code:
#packages
require(tidyverse)
require(ggplot2)
require(visreg)

[repro.data.csv](https://github.com/user-attachments/files/23973533/repro.data.csv)

#data 
stick.mod<-read.csv(file=file.path(dir.output,"repro.data.csv"))

#model
stick.l.8<- glm(avg.length ~ f.Region + summer.temp + summer.wind, data=stick.mod, weights= 1/stick.l.var)
summary(stick.l.8)

#visreg call
visreg(stick.l.8, scale="response")

Then I get:
Error in eval(extras, data, env) : object 'stick.l.var' not found as in it cannot see that variable within the dataframe, but when I interrogate the model object, stick.l.var does exist within the data= data.frame. 

I have tried some work arounds like making a separate weights vector for the model but it does not like that either. It works fine for other models that are not utilizing the weights argument.

I am using R version 4.5.1 (2025-06-13 ucrt), and visreg 2.8.0

Thanks for any and all help,

Elena

**Comment by pbreheny** [comment] 2025-12-11 22:59
Hi @e-eberhardt,

This *is* a bug, but it doesn't have anything to do with the glmmTMB issue, so I opened a separate issue for it: #131 

I should fix it, but in the meantime, you can avoid the problem if you convert f.Region to a factor prior to fitting the glm.
